### ISSUE TITLE
Minimum width screen size

### ISSUE THREAD

**Issue by glynhudson** [openenergymonitor/cydynni-cordova#3]
Needs to be set to fit on iphone5 320px 

![img_0010](https://cloud.githubusercontent.com/assets/758844/19767280/f5b576ba-9c49-11e6-9820-2531c86c0716.PNG)

**Comment by davehun** [comment]
what does the website look like on iphone 5 ?

**Comment by glynhudson** [comment]
Different, the width is better (at least on the tips view) but the height does not fit the 'next'and previous buttons 

![img_0012](https://cloud.githubusercontent.com/assets/758844/19776655/d82664b0-9c6c-11e6-9757-af82c1b1e063.PNG)

Pie chart button dont quit fit:

![img_0011 1](https://cloud.githubusercontent.com/assets/758844/19776661/e2dfaefc-9c6c-11e6-85da-f4d8f6597518.PNG)

**Comment by davehun** [comment]
hmm might be worth trying to fix the site and re visit ? @TrystanLea thoughts  ?
could also try a re build with 
EnableViewportScale(true) 
https://cordova.apache.org/docs/en/latest/config_ref/

**Comment by davehun** [comment]
ok new build for testing 1.2.0 let me know if it makes any difference

**Comment by davehun** [comment]
doesnt appear to in the simulator though

**Comment by glynhudson** [comment]
Can't see 1.2.0 on test flight yet. I'll look tomorrow

**Comment by glynhudson** [comment]
fixed
