### ISSUE TITLE
iOS version is still using the default cordova icon

### ISSUE THREAD

**Issue by glynhudson** [openenergymonitor/cydynni-cordova#4]
![img_0019](https://cloud.githubusercontent.com/assets/758844/20524780/0a100368-b0b4-11e6-9103-d40df274de49.PNG)

Offline message appears for a short time at startup, this is not a big deal. Maybe it appears for a bit longer on a 5c since it's slower.

**Comment by glynhudson** [comment]
I think I've figured out why, we need to create some more icon sets. I'll get on it with @SlyRemarks

**Comment by davehun** [comment]
was just looking at that
